POST {{BASE_URL}}/users
Content-Type: application/json

< ./json/api.users.json

{%
  local body = context.json_decode(context.result.body)

  context.set_env("TOKEN", body.user.token)
%}

###
POST {{BASE_URL}}/users/login
Content-Type: application/json

< ./json/api.users.login.json
{%
  local body = context.json_decode(context.result.body)

  context.set_env("TOKEN", body.user.token)
%}

