POST {{BASE_URL}}/users
Content-Type: application/json

{
  "user": {
      "username":  "johndoe",
      "email":     "doe@john.com",
      "firstName": "John",
      "lastName":  "Doe",
      "password":  "securepassword"
  }
}


